name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t deploy-test .
    - name: Test application
      run: |
        docker run --name test-container -d -p 8088:80 deploy-test .
        sleep 20
        curl --retry 5 --retry-delay 5 http://localhost:8088 | grep "Hello, CI/CD!"
        docker stop test-container
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.muatib }}
        password: ${{ secrets.Fisherman2829 }}
    - name: Push to Docker Hub
      run: |
        docker tag deploy-test . ${{ secrets.DOCKER_USERNAME }}/deploy-test:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/deploy-test:latest
